package com.github.xandergos.terraindiffusionmc.world;

import com.github.xandergos.terraindiffusionmc.pipeline.LocalTerrainProvider;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.levelgen.DensityFunction;
import net.minecraft.world.level.levelgen.DensityFunctions;
import net.minecraft.world.level.levelgen.carver.CarverConfiguration;
import net.minecraft.world.level.levelgen.carver.CarvingContext;

/**
 * Deterministic cave hydrology for Terrain Diffusion dimensions: with aquifers disabled,
 * vanilla floods every carved block below sea level. Caves under land (terrain surface at
 * or above sea level) are carved to air instead; caves under oceans keep vanilla flooding.
 * Lava below the carver's lava level is untouched.
 *
 * <p>Called once per carved block, so the per-context facts — whether the dimension is
 * ours and the carver's lava level — are memoized per thread on context/config identity.
 */
public final class CarverHydrology {

    /** Matches sea_level in worldgen/noise_settings/terrain_diffusion.json. */
    private static final int SEA_LEVEL = 63;

    private static final class Memo {
        CarvingContext context;
        boolean terrainDiffusion;
        CarverConfiguration config;
        int lavaY;
    }

    private static final ThreadLocal<Memo> MEMO = ThreadLocal.withInitial(Memo::new);

    private CarverHydrology() {
    }

    /**
     * Returns the carve state override for this position, or {@code null} to let
     * vanilla decide.
     */
    public static BlockState carveStateOverride(CarvingContext context, CarverConfiguration config, BlockPos pos) {
        Memo memo = MEMO.get();
        if (memo.context != context) {
            memo.context = context;
            memo.config = null;
            // The router codec wraps parsed density functions in HolderHolder, so unwrap
            // before checking whether this dimension is generated by Terrain Diffusion.
            DensityFunction finalDensity = context.randomState().router().finalDensity();
            if (finalDensity instanceof DensityFunctions.HolderHolder holder) {
                finalDensity = holder.function().value();
            }
            memo.terrainDiffusion = finalDensity instanceof TerrainDiffusionDensityFunction;
        }
        if (!memo.terrainDiffusion) {
            return null;
        }
        if (memo.config != config) {
            memo.config = config;
            memo.lavaY = config.lavaLevel.resolveY(context);
        }
        if (pos.getY() <= memo.lavaY) {
            return null;
        }
        int surface = LocalTerrainProvider.surfaceHeight(pos.getX(), pos.getZ());
        if (surface == Integer.MIN_VALUE || surface < SEA_LEVEL) {
            return null;
        }
        return Blocks.AIR.defaultBlockState();
    }
}
