package com.github.xandergos.terraindiffusionmc.mixin;

import com.github.xandergos.terraindiffusionmc.world.TerrainDiffusionDensityFunction;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.levelgen.Aquifer;
import net.minecraft.world.level.levelgen.DensityFunction;
import net.minecraft.world.level.levelgen.DensityFunctions;
import net.minecraft.world.level.levelgen.carver.CarverConfiguration;
import net.minecraft.world.level.levelgen.carver.CarvingContext;
import net.minecraft.world.level.levelgen.carver.WorldCarver;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Deterministic cave hydrology: with aquifers disabled, vanilla floods every
 * carved block below sea level. Caves under land (terrain surface at or above
 * sea level) are carved to air instead; caves under oceans keep vanilla
 * flooding. Lava below the carver's lava level is untouched.
 */
@Mixin(WorldCarver.class)
public class WorldCarverMixin {

    /** Matches sea_level in worldgen/noise_settings/terrain_diffusion.json. */
    @Unique
    private static final int SEA_LEVEL = 63;

    @Inject(method = "getCarveState", at = @At("HEAD"), cancellable = true)
    private void terrainDiffusionMc$dryLandCaves(CarvingContext context, CarverConfiguration config,
                                                 BlockPos pos, Aquifer aquifer,
                                                 CallbackInfoReturnable<BlockState> cir) {
        // Only act in dimensions generated by Terrain Diffusion. The router codec
        // wraps parsed density functions in HolderHolder, so unwrap before checking.
        DensityFunction finalDensity = context.randomState().router().finalDensity();
        if (finalDensity instanceof DensityFunctions.HolderHolder holder) {
            finalDensity = holder.function().value();
        }
        if (!(finalDensity instanceof TerrainDiffusionDensityFunction)) {
            return;
        }
        if (pos.getY() <= config.lavaLevel.resolveY(context)) {
            return;
        }
        int surface = TerrainDiffusionDensityFunction.terrainSurfaceHeight(pos.getX(), pos.getZ());
        if (surface == Integer.MIN_VALUE) {
            return;
        }
        if (surface >= SEA_LEVEL) {
            cir.setReturnValue(Blocks.AIR.defaultBlockState());
        }
    }
}
